channels:
  - conda-forge
  - defaults
dependencies:
  - scikit-learn 
  - pandas 
  - pyarrow
  - numpy
  - pytest
  - sympy
  - pyyaml
  - pip 
  - pip:
    - git+https://github.com/EpistasisLab/pmlb
    - pytest-order
    - eco2ai
    - tabulate
