channels:
  - conda-forge
  - defaults
dependencies:
  - scikit-learn 
  - pandas<3
  - pyarrow
  - numpy<2
  - pytest
  - sympy
  - pyyaml
  - setuptools<72
  - pip 
  - pip:
    - git+https://github.com/EpistasisLab/pmlb
    - pytest-order
    - eco2ai
    - tabulate
    - "numpy<2"
