name: ellyn-env
channels:
    - conda-forge
dependencies:
    - python=3.9
    - eigen=3.3.7
    - boost=1.74.0
    - scikit-learn
    - pandas
    - pip
    - pip:
        - DistanceClassifier
    # - setuptools=45.*
    # - wheel=0.35.*
    # - pip=20.*
    # - pip:
