channels:
    - conda-forge
dependencies:
    - python=3.10
    - pip
    - numpy
    - sympy
    - scikit-learn
    - scipy
    - pyyaml
    - pip:
        - jax[cpu]>=0.4.26
        - flax
        - optax
